site_name: JackDonnelly.tk
site_url: httpp://www.jackdonnelly.tk
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
plugins:
  - glightbox

nav:
    - Home: index.md
    - Test page: Testpage.md


theme:
    name: mkdocs
    favicon: assets/icon.png
    nav_style: dark
    logo: assets/logo.png
    palette:
        primary: blue grey
        scheme: slate
        accent: amber

copyright: <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.
