site_name: jdonnelly.org
site_author: Jack Donnelly
site_url: jdonnelly.org
site_description: >-
    Digital Portfolio For Jack Donnelly - A Student, Engineer, and Programmer.


markdown_extensions:
  - meta
  - attr_list
  - md_in_html
plugins:
  - glightbox


repo_url: https://github.com/Jdonnelly733/JackDonnelly
repo_name: Jdonnelly733/JackDonnelly


nav:
    - Home: index.md
    - Test page: Testpage.md
    - About Me: bio.md


theme:
    name: material
    
    font:
      text: Raleway
      code: Exo 2
    favicon: assets/icon.png
    nav_style: dark
    logo: assets/Header.png
    palette:
    - scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


copyright: <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.
